<?xml version='1.1' encoding='UTF-8'?>
<hudson.maven.MavenModuleSetBuild plugin="maven-plugin@3.27">
  <actions>
    <hudson.model.CauseAction>
      <causeBag class="linked-hash-map">
        <entry>
          <hudson.model.Cause_-UserIdCause>
            <userId>javier</userId>
          </hudson.model.Cause_-UserIdCause>
          <int>1</int>
        </entry>
      </causeBag>
    </hudson.model.CauseAction>
    <jenkins.metrics.impl.TimeInQueueAction plugin="metrics@4.2.37-489.vb_6db_69b_ce753">
      <queuingDurationMillis>27</queuingDurationMillis>
      <blockedDurationMillis>0</blockedDurationMillis>
      <buildableDurationMillis>13</buildableDurationMillis>
      <waitingDurationMillis>9</waitingDurationMillis>
    </jenkins.metrics.impl.TimeInQueueAction>
    <hudson.plugins.git.util.BuildData plugin="git@5.8.0">
      <buildsByBranchName>
        <entry>
          <string>refs/remotes/origin/main</string>
          <hudson.plugins.git.util.Build>
            <marked plugin="git-client@6.4.0">
              <sha1>b5a630b1994b5b2f3f590d1c398612cf6b955a59</sha1>
              <branches class="list">
                <hudson.plugins.git.Branch>
                  <sha1 reference="../../../sha1"/>
                  <name>refs/remotes/origin/main</name>
                </hudson.plugins.git.Branch>
              </branches>
            </marked>
            <revision reference="../marked"/>
            <hudsonBuildNumber>5</hudsonBuildNumber>
          </hudson.plugins.git.util.Build>
        </entry>
      </buildsByBranchName>
      <lastBuild reference="../buildsByBranchName/entry/hudson.plugins.git.util.Build"/>
      <scmName></scmName>
      <remoteUrls>
        <string>https://github.com/spring-projects/spring-petclinic.git</string>
      </remoteUrls>
    </hudson.plugins.git.util.BuildData>
    <hudson.scm.SCMRevisionState_-None/>
    <hudson.maven.reporters.MavenAggregatedArtifactRecord>
      <records/>
      <parent reference="../../.."/>
    </hudson.maven.reporters.MavenAggregatedArtifactRecord>
    <hudson.tasks.Fingerprinter_-FingerprintAction>
      <record>
        <entry>
          <string>org.attoparser:attoparser-2.0.7.RELEASE.jar</string>
          <string>fd09ceba7061e05460e74e0e1e64f233</string>
        </entry>
        <entry>
          <string>org.checkerframework:checker-qual-3.49.5.jar</string>
          <string>a6525c2747603fb3ec22d18c4adc7419</string>
        </entry>
        <entry>
          <string>org.springframework:spring-beans-7.0.0-RC3.jar</string>
          <string>50e369740bd966e3c4ac634ace358125</string>
        </entry>
        <entry>
          <string>org.springframework:spring-aspects-7.0.0-RC3.jar</string>
          <string>94e7928a631c793e352627f04c69da91</string>
        </entry>
        <entry>
          <string>org.apache.tomcat.embed:tomcat-embed-core-11.0.13.jar</string>
          <string>1e06b4345caf8a4ca3f478d87776abbb</string>
        </entry>
        <entry>
          <string>org.glassfish.jaxb:jaxb-core-4.0.6.jar</string>
          <string>e36c915cf47342b4fe31ffba3407b928</string>
        </entry>
        <entry>
          <string>org.apiguardian:apiguardian-api-1.1.2.jar</string>
          <string>8c7de3f82037fa4a2e8be2a2f13092af</string>
        </entry>
        <entry>
          <string>org.junit.platform:junit-platform-engine-6.0.1.jar</string>
          <string>5b533f60bb8146253e3ee366a9261198</string>
        </entry>
        <entry>
          <string>org.mockito:mockito-core-5.20.0.jar</string>
          <string>05f1af408a8a9599b65453c3c3082f6e</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-http-client-4.0.0-RC2.jar</string>
          <string>8ba9c47ba7a94d8d89ed389f886e31cd</string>
        </entry>
        <entry>
          <string>org.thymeleaf:thymeleaf-3.1.3.RELEASE.jar</string>
          <string>6a513160c67d236d380af821e3a1d093</string>
        </entry>
        <entry>
          <string>com.jayway.jsonpath:json-path-2.9.0.jar</string>
          <string>e89678d2e4ff45e4f39a97ccd0223719</string>
        </entry>
        <entry>
          <string>org.springframework:spring-web-7.0.0-RC3.jar</string>
          <string>2575a1c88197e034ef2f011d7e7e208a</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-dependencies:spring-boot-dependencies-4.0.0-RC2.pom</string>
          <string>1deec4c32463de44651aef68e67699b8</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-webmvc-test-4.0.0-RC2.jar</string>
          <string>2498fec9d3909212a12cbc5609c684b3</string>
        </entry>
        <entry>
          <string>org.testcontainers:testcontainers-2.0.1.jar</string>
          <string>ba88720c17e4978c8654505513e90f5d</string>
        </entry>
        <entry>
          <string>jakarta.persistence:jakarta.persistence-api-3.2.0.jar</string>
          <string>79acec18d202797dcba1fff596a47684</string>
        </entry>
        <entry>
          <string>io.micrometer:micrometer-core-1.16.0-RC1.jar</string>
          <string>d39a66964429d28b551647797b5bdacb</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-data-jpa-4.0.0-RC2.jar</string>
          <string>54a7d001bf2a1a7b5921a41ecefbaa18</string>
        </entry>
        <entry>
          <string>org.apache.logging.log4j:log4j-to-slf4j-2.25.2.jar</string>
          <string>381a456c8315d101e3e2ef33ec470654</string>
        </entry>
        <entry>
          <string>org.springframework:spring-test-7.0.0-RC3.jar</string>
          <string>7395acc745ca59ee0d848d8fec2f66bc</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-actuator-autoconfigure-4.0.0-RC2.jar</string>
          <string>5b0a6e756025b4e9c4dce1a06cce1c45</string>
        </entry>
        <entry>
          <string>io.micrometer:micrometer-jakarta9-1.16.0-RC1.jar</string>
          <string>0090e07efad702848da44db499adfdb5</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-jpa-4.0.0-RC2.jar</string>
          <string>6826182701d43c10bc31af1048c66286</string>
        </entry>
        <entry>
          <string>org.springframework.data:spring-data-jpa-4.0.0-RC2.jar</string>
          <string>d0299738bb73074b0e56d8197cc6f61e</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-thymeleaf-4.0.0-RC2.jar</string>
          <string>8bdf3fc7f9bd7d423b84415ce74fca0f</string>
        </entry>
        <entry>
          <string>org.webjars:webjars-locator-lite-1.1.1.jar</string>
          <string>61d1d2035003242caf26938bc2cbdec5</string>
        </entry>
        <entry>
          <string>org.thymeleaf:thymeleaf-spring6-3.1.3.RELEASE.jar</string>
          <string>1953618cce1d2d7d685ac95420056bc7</string>
        </entry>
        <entry>
          <string>jakarta.validation:jakarta.validation-api-3.1.1.jar</string>
          <string>93ce96e77734f4280157edeffcae44e8</string>
        </entry>
        <entry>
          <string>net.minidev:json-smart-2.6.0.jar</string>
          <string>fde8981f31c3b972355a5adf26a9ec65</string>
        </entry>
        <entry>
          <string>jakarta.transaction:jakarta.transaction-api-2.0.1.jar</string>
          <string>5315974a3935e342b40849478e1c9966</string>
        </entry>
        <entry>
          <string>com.google.errorprone:error_prone_annotations-2.43.0.jar</string>
          <string>59fe4a79ce3218423f4f8918f04ef22f</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-actuator-4.0.0-RC2.jar</string>
          <string>2b7456c5c64125c75af896ccb30228a2</string>
        </entry>
        <entry>
          <string>org.glassfish.jaxb:jaxb-runtime-4.0.6.jar</string>
          <string>0e600d639f3a09ddd6fa91623a12b634</string>
        </entry>
        <entry>
          <string>org.hamcrest:hamcrest-3.0.jar</string>
          <string>781023c38b054e9cf1c818c77895e1eb</string>
        </entry>
        <entry>
          <string>org.opentest4j:opentest4j-1.3.0.jar</string>
          <string>03c404f727531f3fd3b4c73997899327</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-validation-4.0.0-RC2.jar</string>
          <string>e4f81eeb7702f62f908381b70608c096</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-tomcat-runtime-4.0.0-RC2.jar</string>
          <string>aa19b526d422366c4f624c78ffacfbfc</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-jdbc-test-4.0.0-RC2.jar</string>
          <string>700da2e3cd22cebd2ec1ca4135a70ba4</string>
        </entry>
        <entry>
          <string>jakarta.activation:jakarta.activation-api-2.1.4.jar</string>
          <string>bc1602eee7bc61a0b86f14bbbb0cc794</string>
        </entry>
        <entry>
          <string>org.antlr:antlr4-runtime-4.13.2.jar</string>
          <string>eecf1908f0cfff10f8bb82878b5ca401</string>
        </entry>
        <entry>
          <string>tools.jackson.core:jackson-databind-3.0.1.jar</string>
          <string>98daade99446031a372437a121a3a4f0</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-test-autoconfigure-4.0.0-RC2.jar</string>
          <string>528495883266e190c76a0a481fd063a0</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-webmvc-4.0.0-RC2.jar</string>
          <string>5e6add018f595f74d4af015094542041</string>
        </entry>
        <entry>
          <string>com.github.ben-manes.caffeine:caffeine-3.2.3.jar</string>
          <string>0258f45d43968523cc11beeb01b240f2</string>
        </entry>
        <entry>
          <string>org.mockito:mockito-junit-jupiter-5.20.0.jar</string>
          <string>34ac767475d435d77ed12d40847fd4a2</string>
        </entry>
        <entry>
          <string>org.springframework:spring-jdbc-7.0.0-RC3.jar</string>
          <string>44f49cc2fe0e7dedbad26312c7bdc78e</string>
        </entry>
        <entry>
          <string>org.springframework:spring-core-7.0.0-RC3.jar</string>
          <string>d886837903678a800e3fc900a23b3a28</string>
        </entry>
        <entry>
          <string>net.minidev:accessors-smart-2.6.0.jar</string>
          <string>0ad72639eea293193f68898da9b0b902</string>
        </entry>
        <entry>
          <string>org.springframework:spring-context-7.0.0-RC3.jar</string>
          <string>198a866c7eae108550ded6bf49cb0272</string>
        </entry>
        <entry>
          <string>commons-codec:commons-codec-1.19.0.jar</string>
          <string>e46fa78c69544eb6239c4e8447e72544</string>
        </entry>
        <entry>
          <string>org.apache.logging.log4j:log4j-api-2.25.2.jar</string>
          <string>4ad7b5c23d86eab187e599a826fa9254</string>
        </entry>
        <entry>
          <string>org.junit.jupiter:junit-jupiter-engine-6.0.1.jar</string>
          <string>527001b6833c8ece15a920d6c88c6c6d</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-persistence-4.0.0-RC2.jar</string>
          <string>389b4457520748cf48ad5817381e2bcd</string>
        </entry>
        <entry>
          <string>net.bytebuddy:byte-buddy-1.17.8.jar</string>
          <string>ac7292226046cb7206b349e21affecfe</string>
        </entry>
        <entry>
          <string>org.postgresql:postgresql-42.7.8.jar</string>
          <string>d5626352279a40e69e863fcff564e2f1</string>
        </entry>
        <entry>
          <string>jakarta.xml.bind:jakarta.xml.bind-api-4.0.4.jar</string>
          <string>6dd465a232e545193ab8ab77cc4fbdb9</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-transaction-4.0.0-RC2.jar</string>
          <string>0897860da68785e896705fb1b80cb413</string>
        </entry>
        <entry>
          <string>tools.jackson.core:jackson-core-3.0.1.jar</string>
          <string>d1058728ed92281e3b84d26dc9c44a4e</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-test-4.0.0-RC2.jar</string>
          <string>22be7f3d45cf8b9e2b89c9800450e198</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-jackson-4.0.0-RC2.jar</string>
          <string>9f48ccbe835b9997510ba4edda4869c4</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-hibernate-4.0.0-RC2.jar</string>
          <string>3b735d90f4bc4efdfdd46c297fc1a76f</string>
        </entry>
        <entry>
          <string>com.h2database:h2-2.4.240.jar</string>
          <string>fb14a47b07dfd4381a608d3adb89dc25</string>
        </entry>
        <entry>
          <string>org.junit.jupiter:junit-jupiter-6.0.1.jar</string>
          <string>c40efdbf94c01ad379b4dcd37e501dad</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-jdbc-4.0.0-RC2.jar</string>
          <string>3afc1466f5b34915ead678195b24fe4c</string>
        </entry>
        <entry>
          <string>org.rnorth.duct-tape:duct-tape-1.0.8.jar</string>
          <string>af347a22d19d632616d7a3fb63024218</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-jdbc-4.0.0-RC2.jar</string>
          <string>2bd6435a7e775212719f8e6375379102</string>
        </entry>
        <entry>
          <string>ch.qos.logback:logback-core-1.5.20.jar</string>
          <string>1ac95175bcce6f6747f755921d1c578f</string>
        </entry>
        <entry>
          <string>com.github.docker-java:docker-java-transport-3.6.0.jar</string>
          <string>3988991ebbff2674fbf7287fc7c69459</string>
        </entry>
        <entry>
          <string>org.testcontainers:testcontainers-database-commons-2.0.1.jar</string>
          <string>e3bb8d99dba4afc47da045d7aea30c36</string>
        </entry>
        <entry>
          <string>org.springframework.data:spring-data-commons-4.0.0-RC2.jar</string>
          <string>a154e86684128e75d595f89824dab377</string>
        </entry>
        <entry>
          <string>com.github.docker-java:docker-java-api-3.6.0.jar</string>
          <string>5bda19310309b053554104eb89aca1b1</string>
        </entry>
        <entry>
          <string>org.hdrhistogram:HdrHistogram-2.2.2.jar</string>
          <string>41f807bf0c681d6f692c408a6e217eaf</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-devtools-4.0.0-RC2.jar</string>
          <string>432ad097fed10f3bde9c20f07f87e8c3</string>
        </entry>
        <entry>
          <string>org.apache.commons:commons-lang3-3.19.0.jar</string>
          <string>2ac2db154e365d55d167ec1215125a3a</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-data-jpa-test-4.0.0-RC2.jar</string>
          <string>3a0e6786dc368f547dff10c4af844c73</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-jackson-test-4.0.0-RC2.jar</string>
          <string>f4e4fa4b2919c67a862878ace53d53b5</string>
        </entry>
        <entry>
          <string>com.sun.istack:istack-commons-runtime-4.1.2.jar</string>
          <string>535154ef647af2a52478c4debec93659</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-data-jpa-test-4.0.0-RC2.jar</string>
          <string>c6debb336f6ede47c81d3aaa91f22af3</string>
        </entry>
        <entry>
          <string>org.jetbrains:annotations-17.0.0.jar</string>
          <string>7b06437ed47fa7b4a8ec8909f4fb9022</string>
        </entry>
        <entry>
          <string>net.java.dev.jna:jna-5.17.0.jar</string>
          <string>08fc1e1f239ec4511e8d9e5a433f6244</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-tomcat-4.0.0-RC2.jar</string>
          <string>c87c24b626a4577b3f9533ff0018dec7</string>
        </entry>
        <entry>
          <string>org.testcontainers:testcontainers-mysql-2.0.1.jar</string>
          <string>2b821f673ea7320b961783678493667e</string>
        </entry>
        <entry>
          <string>io.micrometer:micrometer-commons-1.16.0-RC1.jar</string>
          <string>f899ed205f8b0cdc53247c4365c4aa5f</string>
        </entry>
        <entry>
          <string>javax.cache:cache-api-1.1.1.jar</string>
          <string>dfdac9358e140e61c574abb1ada84dc9</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-4.0.0-RC2.jar</string>
          <string>780fa394d20ab9c1a675fe2f999bb6b0</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-jdbc-test-4.0.0-RC2.jar</string>
          <string>1fff3203bfce9515a8a52aba8a55d754</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-restclient-4.0.0-RC2.jar</string>
          <string>316393f10acf0ff25dde47209e8a49fe</string>
        </entry>
        <entry>
          <string>org.eclipse.angus:angus-activation-2.0.3.jar</string>
          <string>ad20392145690b36b4f950fe31a31a2a</string>
        </entry>
        <entry>
          <string>org.jspecify:jspecify-1.0.0.jar</string>
          <string>9133aba420d0ca3b001dbb6ae9992cf6</string>
        </entry>
        <entry>
          <string>com.fasterxml.jackson.core:jackson-annotations-2.20.jar</string>
          <string>b901def3c20752817f27130e4b8d6640</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-restclient-4.0.0-RC2.jar</string>
          <string>53b90eef35f9275a9d42fbc51da34803</string>
        </entry>
        <entry>
          <string>org.springframework:spring-orm-7.0.0-RC3.jar</string>
          <string>ff50ad4c1c8899f3d9124b15344fecfa</string>
        </entry>
        <entry>
          <string>org.unbescape:unbescape-1.1.6.RELEASE.jar</string>
          <string>d95ed94e1624e307a1958ee105ccbf39</string>
        </entry>
        <entry>
          <string>org.slf4j:jul-to-slf4j-2.0.17.jar</string>
          <string>a42936c56611e4794c42908fb3d3a647</string>
        </entry>
        <entry>
          <string>org.springframework:spring-context-support-7.0.0-RC3.jar</string>
          <string>9bf2617025b7a11b0961001737bf3d56</string>
        </entry>
        <entry>
          <string>org.testcontainers:testcontainers-jdbc-2.0.1.jar</string>
          <string>c8d730b2adde07266545d44b94b57b93</string>
        </entry>
        <entry>
          <string>org.webjars.npm:font-awesome-4.7.0.jar</string>
          <string>d01d4fbc4870714c76341ca06ea80525</string>
        </entry>
        <entry>
          <string>org.testcontainers:testcontainers-junit-jupiter-2.0.1.jar</string>
          <string>829eb1ac2bb582c88dd87b56992028a3</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-restclient-test-4.0.0-RC2.jar</string>
          <string>7584fc5c88396b9df407f20848de014d</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-cache-4.0.0-RC2.jar</string>
          <string>25eb28804a42b4351684113493f1a38f</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-resttestclient-4.0.0-RC2.jar</string>
          <string>1479b38fcef47ceaffa49245f24be90f</string>
        </entry>
        <entry>
          <string>org.ow2.asm:asm-9.7.1.jar</string>
          <string>e2cdd32d198ad31427d298eee9d39d8d</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-data-commons-4.0.0-RC2.jar</string>
          <string>4a495c71375eaef2f6f180a780500ca3</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-autoconfigure-4.0.0-RC2.jar</string>
          <string>eac3c52b0b9e9add133f6e5a6e102a4e</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-jpa-test-4.0.0-RC2.jar</string>
          <string>8d231b3bda2de1111ed320da9eb9680a</string>
        </entry>
        <entry>
          <string>org.hibernate.orm:hibernate-core-7.1.6.Final.jar</string>
          <string>32fab73bf0a1f40ff88c26fbf28bafc5</string>
        </entry>
        <entry>
          <string>org.springframework:spring-expression-7.0.0-RC3.jar</string>
          <string>6d3c9a9312e083484d23a430fa736021</string>
        </entry>
        <entry>
          <string>org.jboss.logging:jboss-logging-3.6.1.Final.jar</string>
          <string>acab989faf62db02c092448e95614fab</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-webmvc-4.0.0-RC2.jar</string>
          <string>ff008313ff6478528fc9079631d26184</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-test-4.0.0-RC2.jar</string>
          <string>08436a673d91d93209581ac7186e3cdf</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-restclient-test-4.0.0-RC2.jar</string>
          <string>6e004cc5b65311e89599ffd1dd524506</string>
        </entry>
        <entry>
          <string>com.mysql:mysql-connector-j-9.4.0.jar</string>
          <string>0db53506cfc6f9c8fe054c09e7bd0904</string>
        </entry>
        <entry>
          <string>io.micrometer:micrometer-observation-1.16.0-RC1.jar</string>
          <string>aff8c27a36382eb76cfa86ac8c1f0f74</string>
        </entry>
        <entry>
          <string>commons-logging:commons-logging-1.3.5.jar</string>
          <string>9ca067b073153c86c2da350c0f2cdf70</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-logging-4.0.0-RC2.jar</string>
          <string>9e8ab6faa6c0f4e91a2830a08f898cf8</string>
        </entry>
        <entry>
          <string>org.assertj:assertj-core-3.27.6.jar</string>
          <string>79563d5e0a3400a566b2105dde08b8e3</string>
        </entry>
        <entry>
          <string>org.hibernate.models:hibernate-models-1.0.1.jar</string>
          <string>911e7ad11382712f0869328465937718</string>
        </entry>
        <entry>
          <string>org.glassfish.jaxb:txw2-4.0.6.jar</string>
          <string>0bf7070aee3bb53640d2ea6441e059fb</string>
        </entry>
        <entry>
          <string>org.slf4j:slf4j-api-2.0.17.jar</string>
          <string>b6480d114a23683498ac3f746f959d2f</string>
        </entry>
        <entry>
          <string>org.webjars.npm:bootstrap-5.3.8.jar</string>
          <string>4a7ab934e7afc1c7f18baa816aabfb2f</string>
        </entry>
        <entry>
          <string>ch.qos.logback:logback-classic-1.5.20.jar</string>
          <string>27d2420a33cc0b18abe75eb7c7c12b27</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-4.0.0-RC2.jar</string>
          <string>69960a6645037b3938fd164bf9ef347a</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-micrometer-observation-4.0.0-RC2.jar</string>
          <string>489a1d22acb7c9306bd51de82324cebc</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-thymeleaf-4.0.0-RC2.jar</string>
          <string>5a1049192da2f34b00c4369131622ba5</string>
        </entry>
        <entry>
          <string>org.awaitility:awaitility-4.3.0.jar</string>
          <string>a40a50a6b70ddd9e31c731ec6c8ed84a</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-webmvc-test-4.0.0-RC2.jar</string>
          <string>b3e21a0ceea7f214e465e3f9eca5ed44</string>
        </entry>
        <entry>
          <string>commons-io:commons-io-2.20.0.jar</string>
          <string>94e7e6b9b5fe82388687b584d3571081</string>
        </entry>
        <entry>
          <string>org.springframework:spring-tx-7.0.0-RC3.jar</string>
          <string>0232ccb0f1af0fb361fa191e928bf488</string>
        </entry>
        <entry>
          <string>jakarta.inject:jakarta.inject-api-2.0.1.jar</string>
          <string>72003bf6efcc8455d414bbd7da86c11c</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-health-4.0.0-RC2.jar</string>
          <string>118b34e7abb87f709a14e871d39353b3</string>
        </entry>
        <entry>
          <string>org.junit.platform:junit-platform-commons-6.0.1.jar</string>
          <string>0096b078430c91f1f93b7fb9f875200f</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-web-server-4.0.0-RC2.jar</string>
          <string>231a2d6f6a087af29ed8868e403fc71c</string>
        </entry>
        <entry>
          <string>org.latencyutils:LatencyUtils-2.0.3.jar</string>
          <string>2ad12e1ef7614cecfb0483fa9ac6da73</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-http-converter-4.0.0-RC2.jar</string>
          <string>8df6d1e98049e6ba3aa2bad1e8aaa0e0</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-micrometer-metrics-4.0.0-RC2.jar</string>
          <string>2fc121245b39ed3ef810cef3e79c4420</string>
        </entry>
        <entry>
          <string>com.fasterxml:classmate-1.7.1.jar</string>
          <string>e64a0680ebc8facde9b4cc431cbc248c</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-validation-4.0.0-RC2.jar</string>
          <string>b1b94913bd1331861a61aacad5913a2d</string>
        </entry>
        <entry>
          <string>org.hibernate.validator:hibernate-validator-9.0.1.Final.jar</string>
          <string>142bc6bcf1a014e768fa962013f3ac1d</string>
        </entry>
        <entry>
          <string>com.vaadin.external.google:android-json-0.0.20131108.vaadin1.jar</string>
          <string>10612241a9cc269501a7a2b8a984b949</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-docker-compose-4.0.0-RC2.jar</string>
          <string>8401152bebcf43a3ad58fa36ddd955cf</string>
        </entry>
        <entry>
          <string>org.aspectj:aspectjweaver-1.9.25.jar</string>
          <string>89f51f6d89cafd0a827dd7180c0c7a72</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-actuator-4.0.0-RC2.jar</string>
          <string>ef00d68f60ba9c60d7af31cb568ef5c3</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-tomcat-4.0.0-RC2.jar</string>
          <string>5a50ac7237e57bd36559f3e82c68ac9b</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-testcontainers-4.0.0-RC2.jar</string>
          <string>c06ca11b0696afb6fcd0cfdf13fbc2c2</string>
        </entry>
        <entry>
          <string>org.xmlunit:xmlunit-core-2.10.4.jar</string>
          <string>f675e71e0cc27f92176dfee932f55dc7</string>
        </entry>
        <entry>
          <string>org.skyscreamer:jsonassert-1.5.3.jar</string>
          <string>aee6947b4d626e3e37c21c7ac7652ae6</string>
        </entry>
        <entry>
          <string>jakarta.annotation:jakarta.annotation-api-3.0.0.jar</string>
          <string>7faffaab962918da4cf5ddfd76609dd2</string>
        </entry>
        <entry>
          <string>org.apache.tomcat.embed:tomcat-embed-el-11.0.13.jar</string>
          <string>327a5d085cfa6bbf0031e1190b9e6b36</string>
        </entry>
        <entry>
          <string>com.github.docker-java:docker-java-transport-zerodep-3.6.0.jar</string>
          <string>53371723a3b18ea4000b637a2a88286a</string>
        </entry>
        <entry>
          <string>org.yaml:snakeyaml-2.5.jar</string>
          <string>8d3b7581db5c7620db55183f33a4f2ad</string>
        </entry>
        <entry>
          <string>org.objenesis:objenesis-3.3.jar</string>
          <string>ab0e0b2ab81affdd7f38bcc60fd85571</string>
        </entry>
        <entry>
          <string>org.springframework.samples:spring-petclinic:pom.xml</string>
          <string>a25c3bea12f236dd03128ae9c8ae3e5e</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-sql-4.0.0-RC2.jar</string>
          <string>22114a275de8ab0bcd57314fe99b2c40</string>
        </entry>
        <entry>
          <string>org.springframework:spring-aop-7.0.0-RC3.jar</string>
          <string>7652c3b97e21224c06021718aefdd9f5</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-cache-4.0.0-RC2.jar</string>
          <string>4f2db5a65d7ade31e3dd3c915a18b20f</string>
        </entry>
        <entry>
          <string>com.zaxxer:HikariCP-7.0.2.jar</string>
          <string>c36937c742c20cbdc7bcb47019e33151</string>
        </entry>
        <entry>
          <string>org.springframework:spring-webmvc-7.0.0-RC3.jar</string>
          <string>a2db70bd460d162f7aee114c9cf6b438</string>
        </entry>
        <entry>
          <string>org.apache.tomcat.embed:tomcat-embed-websocket-11.0.13.jar</string>
          <string>33f87498448f378a7d7072f5ac5b25b7</string>
        </entry>
        <entry>
          <string>org.junit.jupiter:junit-jupiter-params-6.0.1.jar</string>
          <string>a18675e046c6af42b8a3b3a804640304</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-parent:spring-boot-starter-parent-4.0.0-RC2.pom</string>
          <string>abc465960b61a24857b31d5a388e6e54</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-data-jpa-4.0.0-RC2.jar</string>
          <string>788eeea61af5574c9a07ea332cfc3230</string>
        </entry>
        <entry>
          <string>net.bytebuddy:byte-buddy-agent-1.17.8.jar</string>
          <string>c6a66a1f26a382fa4727a74a7f197ed5</string>
        </entry>
        <entry>
          <string>org.apache.commons:commons-compress-1.28.0.jar</string>
          <string>f33efe616d561f8281ef7bf9f2576ad0</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-servlet-4.0.0-RC2.jar</string>
          <string>ea251cdb59ad6a57eaddfbb6fab6bbeb</string>
        </entry>
        <entry>
          <string>org.junit.jupiter:junit-jupiter-api-6.0.1.jar</string>
          <string>13c345298eea2b62b3385271b716e6aa</string>
        </entry>
        <entry>
          <string>org.springframework.boot:spring-boot-starter-jackson-4.0.0-RC2.jar</string>
          <string>ce9e53adc79bcd1b061636ccef980a0b</string>
        </entry>
      </record>
    </hudson.tasks.Fingerprinter_-FingerprintAction>
    <hudson.tasks.MailMessageIdAction plugin="mailer@522.va_995fa_cfb_8b_d">
      <messageId>&lt;126400508.5.1763539552400@d0024fb72bd4&gt;</messageId>
    </hudson.tasks.MailMessageIdAction>
  </actions>
  <queueId>1633</queueId>
  <timestamp>1763539509998</timestamp>
  <startTime>1763539510047</startTime>
  <result>FAILURE</result>
  <duration>42226</duration>
  <charset>UTF-8</charset>
  <keepLog>false</keepLog>
  <builtOn></builtOn>
  <workspace>/var/jenkins_home/workspace/curso-20251117/PetClinic</workspace>
  <hudsonVersion>2.528.2</hudsonVersion>
  <scm class="hudson.plugins.git.GitChangeLogParser" plugin="git@5.8.0">
    <authorOrCommitter>false</authorOrCommitter>
    <showEntireCommitSummaryInChanges>true</showEntireCommitSummaryInChanges>
  </scm>
  <culprits class="java.util.Collections$UnmodifiableSet">
    <c class="sorted-set"/>
  </culprits>
  <mavenVersionUsed>3.9.11</mavenVersionUsed>
</hudson.maven.MavenModuleSetBuild>